### PR TITLE
Make it clear that footswitch needs to be run with sudo.

### PR DESCRIPTION
**Pull request by torsava**
To prevent people from being as confused as I was, vis-à-vis issue #17.

### CODE REVIEW

**Comment by rgerganov** [comment]
footswitch can run with non-root user if you install the udev rules. Did you run 'make install' to do that?

**Comment by torsava** [comment]
I did run the installation exactly according to the manual:

    make
    sudo make install

I'm not sure how to install the udev rules otherwise. Now footswitch works flawlessly with sudo and not at all without.

What should I try?

**Comment by rgerganov** [comment]
The udev rules enable running footswitch with non-root users and they are installed with 'make install'. I tested them only on Ubuntu and you mentioned that you're running Fedora. I will appreciate if you find out how to make them work on your distro and fix the Makefile. Thanks!

**Comment by torsava** [comment]
Ok, I'll try to get to it this week.

However, I think you should mention that if it doesn't run without sudo people should try it with it, as not everyone will be on a supported distribution.

**Comment by torsava** [comment]
So, sadly I was not able to resolve the situation. I really know nothing about udev rules and thus my skills are not up to the task even after I tried to read up on it a bit.

The only thing that might help you is, if `keymap` is supposed to be an executable (as the placement in `RUN` might suggest), there's no such executable available for Fedora at all.

**Comment by torsava** [comment]
Thankfully simply calling footswitch with sudo to configure it is enough to resolve any problems, so I don't really see the need for udev rules.

**Comment by hanwin** [comment]
Hi
I've just find out how to be able to run the tool without to be root(sudo) in Ubuntu 14.04.5
Just change line #1 in the file "19-footswitch.rules" to:
ATTR{product}=="FootSwitch*"\

**Comment by rgerganov** [comment]
This is no longer an issue with the updated udev rules.

**Pull request closed without merging**
