### PR TITLE
Added F13-F24 keys

### PR DESCRIPTION
**Pull request by cob16**
These keys are not present on regular keyboards therefore are desirable for actions that are only wanted on the foot-switch itself.

### CODE REVIEW

**Comment by rgerganov** [comment]
Thanks for the patch. We already have mappings for these keys but under different names:

```
    {"XF86Tools",   0x68},
    {"XF86Launch5", 0x69},
    {"XF86MenuKB",  0x6a},
    {"XF86Launch7", 0x6b},
    {"XF86Launch8", 0x6c},
    {"XF86Launch9", 0x6d},
    {"<6e>",        0x6e},
    {"<6f>",        0x6f},
    {"XF86TouchpadToggle", 0x70},
    {"XF86TouchpadToggle", 0x71},
    {"XF86TouchpadOff",    0x72},
    {"<73>",        0x73},
```
I think it's better to change the names of the existing mappings instead of adding new ones with the same values.
Could you provide a reference doc which shows that these values correspond to F13-F24 keys?

**Comment by cob16** [comment]
I just used the the commented link at the top of the array to find these numbers: 
> http://www.freebsddiary.org/APC/usb_hid_usages.php

Now that you mention it, this reference is not always one to one. Perhaps it will be worth it worth making some sort of alias system? Or more simplicity just to have the duplicates.

Let me know what you think.

**Comment by rgerganov** [comment]
Let's keep it simple and have duplicates. For example, with your patch both `F13` and `XF86Tools` will encode to `0x68`. Reading the programmed key will return whatever is first in the `keymap` table which in this case will be `F13`. Let me know if you are OK with this behavior and I will merge the patch.

**Comment by cob16** [comment]
Sounds good. 👍

**Pull request merged**
